use std::{mem::ManuallyDrop, ops::Deref};

// An implementation of the `Result` type using explicitly tagged unions
//
// fix the TODOs, and veryify that your implementation mirrors the one of `std::result::Result`
// using tests.
//
// > cargo test -p F3-tagged-union

/// RocResult matches the memory layout of a result type generated by the roc compiler. By
/// mirorring the layout on the rust side, values can be passed between roc and rust without any
/// (de)serialization cost
struct RocResult<T, E> {
    tag: RocResultTag,
    payload: RocResultUnion<T, E>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum RocResultTag {
    Ok,
    Err,
}

// HINT: read the documentation of ManuallyDrop, and see what methods it provides
union RocResultUnion<T, E> {
    ok: ManuallyDrop<T>,
    err: ManuallyDrop<E>,
}

impl<T, E> Drop for RocResult<T, E> {
    fn drop(&mut self) {
        // implement drop. Make sure values wrapped in a ManuallyDrop are dropped correctly!
        match self.tag {
            RocResultTag::Ok => unsafe {
                ManuallyDrop::drop(&mut self.payload.ok);
            },
            RocResultTag::Err => unsafe {
                ManuallyDrop::drop(&mut self.payload.err);
            },
        }
    }
}

impl<T: Clone, E: Clone> Clone for RocResult<T, E> {
    fn clone(&self) -> Self {
        match self.tag {
            RocResultTag::Ok => RocResult::ok(unsafe { self.payload.ok.deref().clone() }),
            RocResultTag::Err => RocResult::err(unsafe { self.payload.err.deref().clone() }),
        }
    }
}

impl<T, E> RocResult<T, E> {
    fn unwrap(self) -> T {
        if self.tag == RocResultTag::Ok {
            unsafe {
                // Read the ManuallyDrop<T> out of the union.
                let md_payload = std::ptr::read(&self.payload.ok);
                // Forget the RocResult shell to prevent its Drop from running on the (now invalid) payload.
                std::mem::forget(self);
                ManuallyDrop::into_inner(md_payload) // Get T
            }
        } else {
            // If it's an Err, self (which is Err(e)) will be dropped when panic unwinds.
            // RocResult::drop will correctly drop the E payload.
            panic!("Called `unwrap` on an Err");
        }
    }

    fn unwrap_err(mut self) -> E {
        if self.tag == RocResultTag::Err {
            unsafe {
                let md_payload = std::ptr::read(&self.payload.err);
                std::mem::forget(self); // Forget self as we've taken its Err payload
                ManuallyDrop::into_inner(md_payload)
            }
        } else {
            // If it's an Ok, self (which is Ok(t)) will be dropped when panic unwinds.
            // RocResult::drop will correctly drop the T payload.
            panic!("Called `unwrap_err` on an Ok");
        }
    }

    fn ok(v: T) -> Self {
        RocResult {
            tag: RocResultTag::Ok,
            payload: RocResultUnion {
                ok: ManuallyDrop::new(v),
            },
        }
    }

    fn err(e: E) -> Self {
        RocResult {
            tag: RocResultTag::Err,
            payload: RocResultUnion {
                err: ManuallyDrop::new(e),
            },
        }
    }

    fn is_ok(&self) -> bool {
        matches!(self.tag, RocResultTag::Ok)
    }

    fn is_err(&self) -> bool {
        matches!(self.tag, RocResultTag::Err)
    }

    fn map<F, U>(mut self, f: F) -> RocResult<U, E>
    where
        F: FnOnce(T) -> U,
    {
        match self.tag {
            RocResultTag::Ok => {
                let value = unsafe { ManuallyDrop::take(&mut self.payload.ok) };
                RocResult::ok(f(value))
            }
            RocResultTag::Err => {
                let err = unsafe { ManuallyDrop::take(&mut self.payload.err) };
                RocResult::err(err)
            }
        }
    }
}

impl<T, E> From<RocResult<T, E>> for Result<T, E> {
    fn from(mut value: RocResult<T, E>) -> Self {
        match value.tag {
            RocResultTag::Ok => {
                let t = unsafe {
                    let md_t = std::ptr::read(&value.payload.ok);
                    ManuallyDrop::into_inner(md_t)
                };
                std::mem::forget(value); // Prevent RocResult::drop on the hollowed 'value'
                Result::Ok(t)
            }
            RocResultTag::Err => {
                let e = unsafe {
                    let md_e = std::ptr::read(&value.payload.err);
                    ManuallyDrop::into_inner(md_e)
                };
                std::mem::forget(value); // Prevent RocResult::drop on the hollowed 'value'
                Result::Err(e)
            }
        }
    }
}

impl<T, E> From<Result<T, E>> for RocResult<T, E> {
    fn from(value: Result<T, E>) -> Self {
        match value {
            Ok(v) => RocResult::ok(v),
            Err(e) => RocResult::err(e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_ok() {
        let ok: RocResult<i32, String> = RocResult::ok(42);

        assert!(ok.is_ok());
        assert!(Result::from(ok).is_ok());
    }

    #[test]
    fn test_is_err() {
        let err: RocResult<(), i32> = RocResult::err(42);

        assert!(err.is_err());
        assert!(Result::from(err).is_err());
    }

    #[test]
    fn test_map() {
        let ok: RocResult<i32, i128> = RocResult::ok(42);

        let ok = ok.map(|n| format!("{n}"));

        assert_eq!(ok.unwrap(), "42");
    }

    #[test]
    fn test_clone_ok() {
        let ok: RocResult<i32, i128> = RocResult::ok(42);

        let ok = ok.map(|n| format!("{n}"));

        let std_ok = Result::from(ok.clone());

        assert_eq!(ok.unwrap(), std_ok.unwrap());
    }

    #[test]
    fn test_clone_err() {
        let err: RocResult<i32, String> = RocResult::err(String::from("Hello World!"));

        let std_err = Result::from(err.clone());

        assert_eq!(err.unwrap_err(), std_err.unwrap_err());
    }
}

fn main() {
    println!("Hello, world!");
}
